### PR TITLE
Candidate -13 text addressing forwarding loops

### PR DESCRIPTION
**Pull request by jhaas-pfrc**
This should ideally be pulled vs. -12, but that's not in the repo.  I'll rebase if that's addressed.

This diff addresses the last bit of commentary on dealing with the forwarding loops.  I finally found the desired citation text as part of all things, CIDR.

### CODE REVIEW

**Comment by ksriram25** [comment]
Some comments (same as in the email message April 29): 

1. You based it on v-10 and that is fine because v-11 and v-12 were basically keep alive. There is only a minor difference: remove a Tab before “The desired origin AS could be…”. 
 
2. Perhaps we can describe “deterministic brief BGP aggregation” a little more clearly. The reader may find the paragraph on it a bit fuzzy. Though the examples in the Appendix B clarify it well. We should say that it is about finding “consistent origin AS”. The reader may also be asking what is the opposite – non-deterministic brief aggregation?

3. In the RPKI world, a route with AS_SET ends up being labeled Invalid and an Invalid route SHOULD be considered ineligible for best path selection. This draft uses “treat-as-withdraw” – that makes sense because after deprecation, an AS_PATH with AS_SET in it would be considered malformed. Perhaps this difference between the drafts is OK? Let us think about it a bit.

4. Perhaps we need to say something about handling AS_SETs in AS4_PATH?
See: https://mailarchive.ietf.org/arch/msg/idr/yAf_AoIGOayxjcBTuN1YgQiaYMY/ 

5.  Section 5.3 “Mitigating Forwarding Loops” seems to repeat Rule 1 and 2 in Section 5.1 of [RFC4632]. Some accuracy or clarity seems lost in the process. I think it may be best to simply refer the reader to Rules 1 and 2 in Section 5.1 of [RFC4632] and then say that … Further discussion of forwarding loops and their relationship to AS_SETs can be found in Appendix C.

6. I think the following paragraph from Appendix C can be worded better. I will try to help with that in a follow-up message. We must cite Rule 2 of Section 5.1 of [RFC4632] – “the "next hop" for the aggregate route should be the null destination”.

   When brief aggregation methods are used, a BGP speaker may receive a
   route containing such less specific destination covering a local more
   specific destination and install it in its routing table since it is
   not prevented from doing so by BGP AS_PATH loop detection.  In such
   circumstances, it is critical that such Autonomous Systems implement
   the recommendations from Section 5.1 of [RFC4632] and have covering
   routes for all destinations it announces to external BGP speakers.

**Comment by jhaas-pfrc** [comment]
>     1. You based it on v-10 and that is fine because v-11 and v-12 were basically keep alive. There is only a minor difference: remove a Tab before “The desired origin AS could be…”.

Done.

>     2. Perhaps we can describe “deterministic brief BGP aggregation” a little more clearly. The reader may find the paragraph on it a bit fuzzy. Though the examples in the Appendix B clarify it well. We should say that it is about finding “consistent origin AS”. The reader may also be asking what is the opposite – non-deterministic brief aggregation?

I've changed this to be consistent rather than deterministic.  See if that reads better.

>     3. In the RPKI world, a route with AS_SET ends up being labeled Invalid and an Invalid route SHOULD be considered ineligible for best path selection. This draft uses “treat-as-withdraw” – that makes sense because after deprecation, an AS_PATH with AS_SET in it would be considered malformed. Perhaps this difference between the drafts is OK? Let us think about it a bit.

As noted in email, treat as withdraw removes it from the rib and does the appropriate work.

>     4. Perhaps we need to say something about handling AS_SETs in AS4_PATH?
>        See: https://mailarchive.ietf.org/arch/msg/idr/yAf_AoIGOayxjcBTuN1YgQiaYMY/

I've added some text. Please review.

>     5. Section 5.3 “Mitigating Forwarding Loops” seems to repeat Rule 1 and 2 in Section 5.1 of [RFC4632]. Some accuracy or clarity seems lost in the process. I think it may be best to simply refer the reader to Rules 1 and 2 in Section 5.1 of [RFC4632] and then say that … Further discussion of forwarding loops and their relationship to AS_SETs can be found in Appendix C.

At least rule 2, as per email discussion.  See update.

>     6. I think the following paragraph from Appendix C can be worded better. I will try to help with that in a follow-up message. We must cite Rule 2 of Section 5.1 of [RFC4632] – “the "next hop" for the aggregate route should be the null destination”.
>        When brief aggregation methods are used, a BGP speaker may receive a
>        route containing such less specific destination covering a local more
>        specific destination and install it in its routing table since it is
>        not prevented from doing so by BGP AS_PATH loop detection.  In such
>        circumstances, it is critical that such Autonomous Systems implement
>        the recommendations from Section 5.1 of [RFC4632] and have covering
>        routes for all destinations it announces to external BGP speakers.

I've tweaked the text, but it still needs work.

**Comment by jhaas-pfrc** [comment]
@ksriram25  I’m good with your additional edits. If there’s nothing else, approve and we can merge.

**Comment by ksriram25** [comment]
@jhaas-pfrc 
Please help. How to approve? I do not see the Approve button to click on.

**Comment by jhaas-pfrc** [comment]
> @jhaas-pfrc Please help. How to approve? I do not see the Approve button to click on.

The workflow is in the "Code" section where you do your review, you can click on review and hit "approved".

In the interest of time, I'll take this as an approval and merge and publish.

**Pull request merged**
